defmodule Ashley.Ideas.Idea do
  use Ash.Resource,
    otp_app: :ashley,
    domain: Ashley.Ideas,
    data_layer: AshPostgres.DataLayer

  postgres do
    table "ideas"
    repo Ashley.Repo
  end

  attributes do
    uuid_primary_key :id

    attribute :prompt, :string do
      allow_nil? false
      public? true
      description "The user's high-level idea"
    end

    attribute :title, :string do
      public? true
      description "AI-generated short title"
    end

    attribute :status, :atom do
      constraints one_of: [:draft, :broken_down, :approved]
      default :draft
      public? true
    end

    attribute :breakdown, :map do
      public? true
      description "JSON map of Kanban cards generated by xAI"
    end

    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  relationships do
    has_one :board, Ashley.Kanban.Board do
      destination_attribute :idea_id
    end
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      accept [:prompt]
    end

    update :update do
      primary? true
      accept [:title, :status, :breakdown]
    end

    action :breakdown, :map do
      argument :id, :uuid, allow_nil?: false

      run fn input, _context ->
        idea = Ash.get!(Ashley.Ideas.Idea, input.arguments.id)

        breakdown = %{
          title: String.slice(idea.prompt, 0, 40) <> "...",
          cards: [
            %{title: "Define core resources", description: "Create Idea, Board, Card resources", status: "todo"},
            %{title: "Implement xAI breakdown", description: "Connect to xAI Grok API", status: "todo"},
            %{title: "Build LiveView page", description: "Create the interactive Kanban UI", status: "todo"},
            %{title: "Add drag-and-drop", description: "Make cards reorderable", status: "todo"}
          ]
        }

        # Create Board + Cards
        board = Ashley.Kanban.Board.create!(%{idea_id: idea.id})

        Enum.with_index(breakdown.cards, fn card, i ->
          Ashley.Kanban.Card.create!(%{
            board_id: board.id,
            title: card.title,
            description: card.description,
            status: String.to_atom(card.status),
            order: i
          })
        end)

        # Bulletproof update using changeset
        changeset = Ash.Changeset.for_update(idea, :update, %{
          title: breakdown.title,
          breakdown: breakdown,
          status: :broken_down
        })

        updated_idea = Ash.update!(changeset)
        {:ok, updated_idea}
      end
    end
  end

  code_interface do
    define :create
    define :read
    define :update
    define :destroy
    define :breakdown, args: [:id]
  end
end
