defmodule Ashley.Ideas.Idea do
  use Ash.Resource,
    otp_app: :ashley,
    domain: Ashley.Ideas,
    data_layer: AshPostgres.DataLayer

  postgres do
    table "ideas"
    repo Ashley.Repo
  end

  attributes do
    uuid_primary_key :id

    attribute :prompt, :string do
      allow_nil? false
      public? true
      description "The user's high-level idea"
    end

    attribute :title, :string do
      public? true
      description "AI-generated short title"
    end

    attribute :status, :atom do
      constraints one_of: [:draft, :broken_down, :approved]
      default :draft
      public? true
    end

    attribute :breakdown, :map do
      public? true
      description "JSON map of Kanban cards generated by xAI"
    end

    create_timestamp :inserted_at
    update_timestamp :updated_at
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      accept [:prompt]
    end

    update :update do
      primary? true
      accept [:title, :status, :breakdown]
    end

    action :breakdown, :map do
      argument :id, :uuid, allow_nil?: false

      run fn input, _context ->
        idea = Ash.get!(Ashley.Ideas.Idea, input.arguments.id)

        breakdown = %{
          title: String.slice(idea.prompt, 0, 40) <> "...",
          cards: [
            %{title: "Define core resources", description: "Create Idea, Board, Card resources", status: "todo"},
            %{title: "Implement xAI breakdown", description: "Connect to xAI Grok API", status: "todo"}
          ]
        }

        changeset = Ash.Changeset.for_update(idea, :update, %{
          title: breakdown.title,
          breakdown: breakdown,
          status: :broken_down
        })

        updated = Ash.update!(changeset)
        {:ok, updated}   # ← THIS WAS THE MISSING PIECE
      end
    end
  end

  code_interface do
    define :create
    define :read
    define :update
    define :destroy
    define :breakdown, args: [:id]
  end
end
