defmodule Ashley.Repo.Migrations.CreateKanbanResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :description, :text
      add :status, :text, default: "todo"
      add :order, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :board_id, :uuid, null: false
    end

    create table(:boards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:cards) do
      modify :board_id,
             references(:boards,
               column: :id,
               name: "cards_board_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:boards) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :idea_id,
          references(:ideas,
            column: :id,
            name: "boards_idea_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false
    end
  end

  def down do
    drop constraint(:boards, "boards_idea_id_fkey")

    alter table(:boards) do
      remove :idea_id
      remove :updated_at
      remove :inserted_at
    end

    drop constraint(:cards, "cards_board_id_fkey")

    alter table(:cards) do
      modify :board_id, :uuid
    end

    drop table(:boards)

    drop table(:cards)
  end
end
